### ISSUE TITLE
Landing Page Improvements

### ISSUE THREAD

**Issue by aubgolympics** [AUBG-Olympics/website#32]
# Fixes and Enhancements for the Landing Page

## Based on the feedback provided from the live demo:

- [x] Fix the issue with the slider component - the weird glitch in the photos - potentially think about replacing them with a suitable video. I think that the issue originates from a wrong link to a resource:
![image](https://github.com/AUBG-Olympics/website/assets/147837706/b1a5d33c-238f-4ff2-93df-ebfb2761e54b)

- [x] Shadow of numbers and letters on mobile looks off
- [x] The size of numbers and letters on mobile is too small
- [x] Potentially change the color of the letters to some other 

## Enhancement: 

- [x] Add a button that navigates to the Sign Up page - the button can potentially say **Sign Up Here**

**Comment by Pastedko** [comment]
On mobile the 'SIGN UP' text is not centered inside the button because of the font we are using. I will try to forcefully center it if we decide to use this font
