### ISSUE TITLE
Navigation Component 

### ISSUE THREAD

**Issue by aubgolympics** [AUBG-Olympics/website#33]
# Fixes and Enhancements

## Based on the feedback provided:

- [x] Glitch and Overlap between the Olympics logo and Hamburger menu
- [x] Opening the navigation on mobile covers the entire page including the navigation bar. Make sure that the popup does not cover the Navigation bar 
- [x] Feedback from Staykov -> Change **Who are we** to **Who we are**, we know who we are, we are not asking. 
- [x] On MacBook Pro 14 inch, the navigation bar looks off 

## Enhancements

- [x] Theme functionality is not available on mobile 
- [x] Discuss how to position each of the items in the navigation bar 

## PR - https://github.com/AUBG-Olympics/website/pull/50

**Comment by Pastedko** [comment]
Regarding feedback from Staykov. I think it should be 'About us' or 'Who are we' - OTHERS are asking who are we. The website is not for us to read but for others.

**Comment by Pastedko** [comment]
I need a final say on what we are going to do with the safari problems.
@g-slavov

**Comment by aubgolympics** [comment]
https://github.com/AUBG-Olympics/website/issues/33#issuecomment-2001965439  - About us is another good option, indeed. Regarding Who are we and Who we are - we are telling the world who we are, it is not their job to ask themselves:
![image](https://github.com/AUBG-Olympics/website/assets/147837706/c9802e4b-25d1-4b74-8b03-d262855f340c)

https://github.com/AUBG-Olympics/website/issues/33#issuecomment-2022590444 - Check out the PR above where I have done some of the fixing.

CC: @Pastedko

**Comment by aubgolympics** [comment]
Regarding the issue with the overlap, I would assume that it has happened because of setting the z-index to 1 both for the navigation bar on mobile and the menu. I modified the z-index of the toolbar to become 2 and we can see this on release.

CC: @Pastedko

**Comment by aubgolympics** [comment]
Closed as completed.
